package constants;

public enum Constants {
    CLIENTES_PRINCIPAL, CIDADE_SPED, PRODUTOS, RET_UNIDADES, REC_VENDEDORES, CONDICOES_PAGTO, TRANSPORTADORAS, CLIENTES_VENDEDORES, FAT_FCI, FAT_CONSISTE
}
